- name: Configure NGINX
  template:
    src: "{{ nginx_config_path }}"
    dest: "/root/lab/ansible/megafon_test/nginx_role/templates/nginx.conf"
  when: configure_nginx | default(true)

- name: Reload NGINX configuration
  command: docker exec "{{ nginx_container_name }}" nginx -s reload
  when: configure_nginx | default(true)

