- name: Проверка доступности HTTP
  uri:
    url: "http://{{ item }}"
    status_code: 200
    timeout: 10
    validate_certs: no
    method: GET
  register: http_result
  ignore_errors: true
  loop: "{{ nginx_vhosts }}"

- name: Вывод об ошибке, если статус не 200
  fail:
    msg: "Ошибка доступности HTTP на {{ nginx_vhosts }}, статус: {{ http_result.status }}"
  when: http_result.status is defined and http_result.status != 200
