    - name: Скачиваем образ Nginx
      docker_image:
        name: nginx
        state: present
        source: pull

    - name: Создаем контейнер Nginx
      docker_container:
        name: "{{ nginx_container_name }}"
        image: "{{ nginx_image }}"
        state: started
        ports:
          - "80:80"
        volumes:
          - "/root/lab/ansible/megafon_test/nginx_role/templates/:/etc/nginx/"
          - "/root/lab/ansible/megafon_test/nginx_role/templates/host1:/usr/share/nginx/host1/"
          - "/root/lab/ansible/megafon_test/nginx_role/templates/host2:/usr/share/nginx/host2/"
        restart_policy: always
      register: container_info

